In [1]:
import numpy as np

In [3]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [4]:
y = x.reshape((3,2))
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [5]:
y = x.reshape((3,5))
print(y)

ValueError: cannot reshape array of size 6 into shape (3,5)

In [11]:
x = np.array([[0,1,2],[3,4,5]] , dtype =np.uint8)
print(x)

print('\n\n reshaping this')
y =np.reshape(x,6) 
print(y)
print(x)

[[0 1 2]
 [3 4 5]]


 reshaping this
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [10]:
y = x.reshape(6) 
print(y)
print(x)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [12]:
y = x.ravel()
print(y)

[0 1 2 3 4 5]


`or`

In [13]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [15]:
y = x.flatten()
print(y)

[0 1 2 3 4 5]


In [18]:
print(x)

[[0 1 2]
 [3 4 5]]


In [16]:
y = x.flatten('C') # Clanguage column order flattern , it is default
print(y)

[0 1 2 3 4 5]


In [17]:
y = x.flatten('F') # Forton language column order flattern 
print(y)

[0 3 1 4 2 5]


In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x.dtype)  # defaults int64 , which is huge

int64


` joiniging 2 arrays`

In [21]:
x = np.array([1,2,3] ,dtype=np.uint8)
y = np.array([4,5,6],dtype=np.uint8)

z= np.stack((x,y))
print(z)

uint8
[[1 2 3]
 [4 5 6]]


In [22]:
x = np.array([1,2,3] ,dtype=np.uint8)
y = np.array([4,5,6],dtype=np.uint8)

z= np.stack((x,y) ,axis=0)
print(z)

[[1 2 3]
 [4 5 6]]


In [25]:
x = np.array([1,2,3] ,dtype=np.uint8)
y = np.array([4,5,6],dtype=np.uint8)

z= np.stack((x,y) ,axis=-1)
print(z)

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]]


In [26]:
x = np.array([1,2,3,4,5] ,dtype=np.uint8)
y = np.array([11,12,13,14,15],dtype=np.uint8)
z= np.stack((x,y) ,axis= 1)
print(z)

[[ 1 11]
 [ 2 12]
 [ 3 13]
 [ 4 14]
 [ 5 15]]


In [27]:
z = x + y

print(z)

[12 14 16 18 20]


In [28]:
x = np.array([1,2,3] ,dtype=np.uint8)
y = np.array([4,5,6],dtype=np.uint8)


z = np.dstack((x,y))  #depth wise stack
print(z)  # 3D structure
print(z.shape)

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


In [29]:
z = np.vstack((x,y))  #vertical wise stack
print(z)
print(z.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [30]:

z = np.hstack((x,y))  #horizontal wise stack
print(z)
print(z.shape)

[1 2 3 4 5 6]
(6,)


In [31]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [32]:
a, b, c = np.split(x,3)
print(a,b,c)

[0 1 2] [3 4 5] [6 7 8]


` split should create equal division or error will come
array split does not result in an equal division')`

In [35]:
try:
    a, b , c = np.split(x,4)
except ValueError:
    print("Split should create equal division")

Split should create equal division


In [38]:
x = np.random.rand(4,4,4)
y, z = np.split(x,2)

print( 'y = ')
print(y)

print('\n\n\n')
print( 'z = ')
print(z)

y = 
[[[0.76055455 0.09212503 0.81768595 0.44582647]
  [0.16764071 0.49584829 0.32257242 0.84443791]
  [0.26217984 0.42942418 0.43487903 0.85560944]
  [0.10392513 0.30231827 0.49248738 0.90044236]]

 [[0.48142317 0.69582655 0.66794278 0.22069594]
  [0.62166239 0.94872424 0.93032553 0.89056338]
  [0.08421503 0.30248198 0.82551064 0.85743096]
  [0.59236442 0.08671285 0.35439184 0.940976  ]]]
z = 
[[[0.54597466 0.20366393 0.04458496 0.14441707]
  [0.07629342 0.54695323 0.9090097  0.55039649]
  [0.30159296 0.11415143 0.42990986 0.21253237]
  [0.97467621 0.45300142 0.24841276 0.78476774]]

 [[0.36673445 0.27519807 0.26217098 0.84883952]
  [0.42870236 0.15470238 0.05550237 0.44303652]
  [0.45254845 0.1899707  0.07594531 0.07764848]
  [0.38548016 0.05459458 0.29471472 0.9999505 ]]]


In [39]:
x = np.random.rand(4,4,4)
y, z = np.dsplit(x,2) #using depth

print( 'y = ')
print(y)

print('\n\n\n')
print( 'z = ')
print(z)


y = 
[[[0.35705531 0.69383832]
  [0.39296098 0.73283293]
  [0.23653187 0.1701702 ]
  [0.95151028 0.67238723]]

 [[0.26988912 0.28076258]
  [0.4816757  0.04531771]
  [0.18745254 0.78963713]
  [0.49994162 0.34406882]]

 [[0.85132597 0.54230718]
  [0.43774443 0.18462892]
  [0.34774397 0.64975994]
  [0.01408578 0.88393394]]

 [[0.01328268 0.81933684]
  [0.07591281 0.7629526 ]
  [0.65208334 0.97236816]
  [0.22096585 0.04662654]]]




z = 
[[[0.66559916 0.17480759]
  [0.58492128 0.29390204]
  [0.34774278 0.56589604]
  [0.59298926 0.32740266]]

 [[0.37416073 0.531534  ]
  [0.65301658 0.45293788]
  [0.39679085 0.67368381]
  [0.82320437 0.48933646]]

 [[0.64980208 0.57634967]
  [0.29058006 0.9535736 ]
  [0.31133934 0.99104301]
  [0.50735791 0.03638263]]

 [[0.94409565 0.47836986]
  [0.83697733 0.27958259]
  [0.4014381  0.41137285]
  [0.14960262 0.95224322]]]


In [40]:
x = np.random.rand(4,4,4)
y, z = np.vsplit(x,2) #vertical

print( 'y = ')
print(y)

print('\n\n\n')
print( 'z = ')
print(z)

y = 
[[[0.3387333  0.6999567  0.05560328 0.37900118]
  [0.12705287 0.40337237 0.70104682 0.7687086 ]
  [0.10113296 0.16891991 0.57828294 0.50537098]
  [0.48081799 0.24229262 0.84975102 0.48331866]]

 [[0.69286832 0.26938516 0.55096961 0.22274174]
  [0.15252338 0.89264015 0.41335393 0.17373328]
  [0.83518456 0.09260023 0.71150128 0.84389121]
  [0.14965154 0.21239541 0.30426388 0.21588886]]]




z = 
[[[0.33264808 0.35029751 0.89344263 0.55111073]
  [0.39701384 0.0628881  0.61451301 0.72967296]
  [0.64462311 0.94844267 0.48166661 0.92009867]
  [0.09792682 0.81487262 0.88422414 0.28747955]]

 [[0.36830199 0.38168942 0.15083138 0.57607396]
  [0.1918633  0.08008054 0.94893742 0.34551991]
  [0.88065587 0.07756887 0.08203324 0.82185889]
  [0.96909326 0.4539958  0.29363507 0.5663459 ]]]


In [41]:
x = np.random.rand(4,4,4)
y, z = np.hsplit(x,2) #hosrixaon

print( 'y = ')
print(y)

print('\n\n\n')
print( 'z = ')
print(z)

y = 
[[[0.35712791 0.83235937 0.30382504 0.68197785]
  [0.77020148 0.51067681 0.48254789 0.53823992]]

 [[0.1778994  0.09031207 0.05416159 0.60617598]
  [0.58370887 0.71717635 0.94659295 0.24318936]]

 [[0.83014659 0.15286518 0.81339266 0.719447  ]
  [0.9465033  0.91438942 0.22621477 0.90220137]]

 [[0.02450254 0.01459085 0.37985945 0.86314879]
  [0.5074162  0.35107578 0.10644009 0.17696806]]]




z = 
[[[0.16019944 0.86166966 0.78672957 0.39097424]
  [0.55293764 0.85676273 0.79804309 0.84545077]]

 [[0.60425674 0.69683393 0.20865043 0.29607618]
  [0.42061342 0.95007587 0.72568434 0.38507242]]

 [[0.42194334 0.4348163  0.8223257  0.70893528]
  [0.77144105 0.97380105 0.03128816 0.14587223]]

 [[0.57132726 0.00271933 0.62729711 0.40617888]
  [0.59645125 0.99742048 0.94687127 0.28233397]]]


In [45]:
x =np.arange(16).reshape(4,4)
print(x)
print('\n\n')
y = np.flip(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [48]:
x =np.arange(16).reshape(4,4)
print(x)
print('\n\n')
y = np.flip(x, axis =1)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [50]:
x =np.arange(16).reshape(4,4)
print(x)
print('\n\n')
y = np.flipud(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [51]:
y = np.roll(x,8)
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [62]:
print(x)
y = np.rot90(x,2)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]
