``` There are 5 general mechanisms for creating arrays:

    Conversion from other Python structures (e.g., lists, tuples)

    Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)

    Reading arrays from disk, either from standard or custom formats

    Creating arrays from raw bytes through the use of strings or buffers

    Use of special library functions (e.g., random)
`

In [2]:
import numpy as np

In [3]:
x = np.array([2,3,1,0])
x = np.array([2, 3, 1, 0])
x = np.array([[1,2.0],[0,0],(1+1j,3.)]) # note mix of tuple and lists,


The default dtype is float64.

In [5]:
x =  np.zeros((2, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


arange() will create arrays with regularly incrementing values. 

In [6]:
print(np.arange(10))


[0 1 2 3 4 5 6 7 8 9]


In [9]:
#can have incremental value even in decimals
print(np.arange(1,5 ,.5))


[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.

The advantage of this creation function is that one can guarantee the number of elements and the starting and end point, which arange() generally will not do for arbitrary start, stop, and step values.

In [10]:
np.linspace(1., 4., 6)  #linspace also contains data in the end, where as in arrange the last number is exclusive

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

ndices() will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension. 
This is particularly useful for evaluating functions of multiple dimensions on a regular grid.

In [11]:
x = np.indices((3,3))
print(x.ndim)
print(x.shape)

3
(2, 3, 3)


In [12]:
print(x)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
