# Ones and Zeros

In [3]:
import numpy as np

x = np.empty([3,3] , np.uint8) # creates a random array 
                               # with range od unit8


print(x)

[[176 216 105]
 [  3   0   0]
 [  0   0   0]]


In [5]:
y = np.eye(3 , dtype=np.uint8) #creates a diagonal with 1 
print(y)

In [7]:
y = np.eye(5 , dtype=np.uint8) #creates a diagonal with 1 
print(y)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [8]:
#diagonals can be shifted with adding k 
y = np.eye(5 , dtype=np.uint8 , k=1) 
print(y)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [10]:
#k can be naegative too 
y = np.eye(5 , dtype=np.uint8 , k=-1) 
print(y)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


`the identity matrix, or sometimes ambiguously called a unit matrix, of size n is the n × n square matrix with ones on the main diagonal and zeros elsewhere.`

In [12]:
y = np.identity(5, dtype=np.uint8)
print(y)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [15]:
y = np.ones((5,3,4), dtype=np.uint8)
print(y)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [16]:
y = np.zeros((5,3,4), dtype=np.uint8)
print(y)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [18]:
# crastes a three dimentisonal array with value of 2
y = np.full((3,3,3), dtype=np.uint16 , fill_value =2 )
print(y)

[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]
