In [1]:
import numpy as np

In [2]:
x = np.tri(3,3,k=-0 ,dtype=np.uint16)
print(x)

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [3]:
x = np.tri(5,5,k=0 ,dtype=np.uint16)
print(x)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]]


In [5]:
x = np.tri(5,5,k=1 ,dtype=np.uint16)
print(x)

[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [4]:
x = np.tri(5,5,k=-1 ,dtype=np.uint16)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [12]:
x = np.ones((5,5),dtype=np.uint)
y = np.tril(x,k=-1)  #triangular matriz
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [ ]:
x = np.ones((5,5),dttype=np.uint8)
y = np.tril(x,k=-1)  # uppertriangular matri
print(y)