# NumPy Ndarray Properties

In [2]:
import numpy as np

In [4]:
x = np.array([[[1,2,3] ,[4,5,6]] , [[0,-1,-2],[-3,-4,5]]], np.int16)

print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4  5]]]


In [8]:
print(x.shape) #gives shape of data structure
print(x.ndim) #gives dimenstion of array
print(x.dtype) #gives data type of array

print(x.size) # gives size of array , total number of elements in array
print(x.nbytes) # gives size in byte consumeed by the array 

(2, 2, 3)
3
int16
12
24


In [9]:
print(x.T) # gives transpose of the directory

[[[ 1  0]
  [ 4 -3]]

 [[ 2 -1]
  [ 5 -4]]

 [[ 3 -2]
  [ 6  5]]]


# Numpy Constants

In [11]:
print(np.NAN) # Not  a number
print(np.inf) #  postitive infinity
print(np.NINF)
print(np.NZERO)
print(np.PZERO)

# scientific constants
print(np.e)
print(np.euler_gamma)
print(np.pi)

nan
inf
-inf
-0.0
0.0
2.718281828459045
0.5772156649015329
3.141592653589793


In [19]:
print(np.isinf(x[0,0,0]))  #Shows which elements are positive or negative infinity

print(np.isposinf(x[0,0,0])) # Shows which elements are positive infinity

print(np.isneginf(x[0,0,0])) # Shows which elements are negative infinity

print(np.isnan(x[0,0,0])) # Shows which elements are Not a Number

False
False
False
False
