In [2]:
import numpy as np

`randint can create a single dimension random array `

In [7]:
x = np.random.randint(low = 0 , high = 9, size = 10)
print(x)

[4 0 1 7 4 6 2 1 6 5]


`rand functions create n dimensional random array`

In [9]:
# creates 2D randon arra u

x = np.random.rand(3,3)
print(x)


[[0.04944079 0.18175611 0.23585996]
 [0.32580017 0.86690311 0.20088432]
 [0.83901906 0.45747591 0.40338354]]


In [ ]:
# creates 5D randon arra u

x = np.random.rand(5,5)
print(x)
